# Generated by Django 4.2.1 on 2025-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                ("slug", models.SlugField(unique=True, verbose_name="标签标识")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="标签描述"
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="标签图标URL",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品标签",
                "verbose_name_plural": "商品标签",
                "db_table": "product_tag",
                "ordering": ["-sort_order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_hot",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_recommend",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="product.producttag",
                verbose_name="商品标签",
            ),
        ),
    ]
