# Generated by Django 4.2.1 on 2025-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_producttag_remove_product_is_hot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttag",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="标签ID"
            ),
        ),
    ]
