# Generated by Django 4.2.1 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="店铺ID"
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="店铺名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="店铺描述"),
                ),
                (
                    "logo_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="店铺Logo URL",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="营业执照号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("active", "营业中"),
                            ("suspended", "暂停营业"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=9,
                        verbose_name="店铺状态",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="店主用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺信息",
                "verbose_name_plural": "店铺信息",
                "db_table": "store",
            },
        ),
    ]
