# Generated by Django 4.2.1 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("product", "0001_initial"),
        ("user", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="评价ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="评分（1-5星）"
                    ),
                ),
                (
                    "images",
                    models.TextField(
                        blank=True, null=True, verbose_name="评价图片（JSON格式）"
                    ),
                ),
                (
                    "reply_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="商家回复内容"
                    ),
                ),
                (
                    "reply_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="是否匿名评价"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderinfo",
                        verbose_name="订单ID",
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        db_column="order_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderitem",
                        verbose_name="订单商品明细ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="商品ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        db_column="store_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                        verbose_name="店铺ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品评价",
                "verbose_name_plural": "商品评价",
                "db_table": "product_review",
            },
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("order_item",), name="uk_order_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="chk_rating",
            ),
        ),
    ]
