# Generated by Django 4.2.1 on 2025-08-15 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["-update_time"],
                "verbose_name": "购物车",
                "verbose_name_plural": "购物车",
            },
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="selected",
            field=models.BooleanField(default=True, verbose_name="是否选中结算"),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="商品数量",
            ),
        ),
    ]
