# Generated by Django 4.2.1 on 2025-08-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="头像URL"
            ),
        ),
    ]
