# Generated by Django 4.2.1 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("product", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="订单ID"
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="订单总金额"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="优惠金额",
                    ),
                ),
                (
                    "freight_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="运费"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="实付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待支付"),
                            ("paid", "已支付"),
                            ("shipped", "已发货"),
                            ("delivered", "已收货"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending_payment",
                        max_length=15,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alipay", "支付宝"),
                            ("wechat", "微信支付"),
                            ("bank_card", "银行卡"),
                            ("cash", "现金"),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "ship_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发货时间"
                    ),
                ),
                (
                    "deliver_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="收货时间"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=50, verbose_name="收件人姓名"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=11, verbose_name="收件人电话"),
                ),
                (
                    "recipient_address",
                    models.CharField(max_length=500, verbose_name="收件地址"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="订单备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        db_column="store_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                        verbose_name="店铺ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order_info",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="明细ID"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="商品名称（快照）"),
                ),
                (
                    "product_image",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="商品图片（快照）",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="商品单价（快照）"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="购买数量")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="小计金额"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderinfo",
                        verbose_name="订单ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="商品ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单商品明细",
                "verbose_name_plural": "订单商品明细",
                "db_table": "order_item",
            },
        ),
    ]
