# Generated by Django 4.2.1 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="支付记录ID"
                    ),
                ),
                (
                    "payment_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="支付流水号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="支付金额"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("alipay", "支付宝"),
                            ("wechat", "微信支付"),
                            ("bank_card", "银行卡"),
                            ("cash", "现金"),
                        ],
                        max_length=9,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="支付渠道"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="第三方交易号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=9,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "paid_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付完成时间"
                    ),
                ),
                (
                    "notify_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回调通知时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderinfo",
                        verbose_name="订单ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "db_table": "payment",
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)), name="chk_payment_amount"
            ),
        ),
    ]
